### ISSUE TITLE
上报服务启用后，收到消息未上报

### ISSUE THREAD

**Issue by Hermes981128** [project-mirai/mirai-api-http#166]
配置信息如下：

```
cors: 
  - *
host: 0.0.0.0
port: 8089
authKey: asdasdasdasdasdasd
cacheSize: 4096
enableWebsocket: false
report: 
  enable: true
  groupMessage: 
    report: true
  friendMessage: 
    report: true
  tempMessage: 
    report: false
  eventMessage: 
    report: false
  destinations:["http://127.0.0.1:8081/qq_message/post"]
  extraHeaders:
{}

heartbeat:
  enable: true
  delay: 1000
  period: 15000
  destinations: []
  extraBody:
{}

  extraHeaders:
{}

```
