### ISSUE TITLE
重启Mirai之后自动更新下载了相关包导致http服务无法访问

### ISSUE THREAD

**Issue by STDSuperman** [project-mirai/mirai-api-http#318]
我的全局配置文件：

```yml
## 该配置为全局配置，对所有Session有效

# 可选，默认值为0.0.0.0
host: '127.0.0.1'

# 可选，默认值为8080
port: 9999

# 可选，默认由插件第一次启动时随机生成，建议手动指定
authKey: 1234567890

# 可选，缓存大小，默认4096.缓存过小会导致引用回复与撤回消息失败
cacheSize: 4096

# 可选，是否开启websocket，默认关闭，建议通过Session范围的配置设置
enableWebsocket: true

# 可选，配置CORS跨域，默认为*，即允许所有域名
cors:
  - '*'

## 消息上报
report:
# 功能总开关
  enable: false
  # 群消息上报
  groupMessage:
    report: false
  # 好友消息上报
  friendMessage:
    report: false
  # 临时消息上报
  tempMessage:
    report: false
  # 事件上报
  eventMessage:
    report: false
  # 上报URL
  destinations: []
  # 上报时的额外Header
  extraHeaders: {}

## 心跳
heartbeat:
  # 功能总开关
  enable: true
  # 启动延迟
  delay: 1000
  # 心跳间隔
  period: 15000
  # 心跳上报URL
  destinations: []
  # 上报时的额外信息
  extraBody: {}
  # 上报时的额外头
  extraHeaders: {}
```
## 复现步骤
在重启之前可正常访问，重启之后有更新下载的过程，最终导致原有的http接口无法访问
