### ISSUE TITLE
console界面可以正常显示接收到的消息，但通过接口获取消息恒定为空

### ISSUE THREAD

**Issue by CNMathon** [project-mirai/mirai-api-http#346]
当前情况为：console界面可以正常显示接收到的消息，但通过接口获取消息恒定为空。

以下为该情况截图：

![console界面截图](https://user-images.githubusercontent.com/44454223/118658806-4ff6bf80-b81f-11eb-918c-380046944b18.png)

![接口获取](https://user-images.githubusercontent.com/44454223/118659005-7f0d3100-b81f-11eb-9891-27e7e1bcbc0f.png)

**Comment by Karlatemp** [comment]
开启了 `WebSocket`?

**Comment by CNMathon** [comment]
> 开启了 `WebSocket`?

是的，`WebSocket` 和 普通 `HTTP` 不能同时存在吗？

**Comment by CNMathon** [comment]
> > 开启了 `WebSocket`?
> 
> 是的，`WebSocket` 和 普通 `HTTP` 不能同时存在吗？

已测试，关闭 `WebSocket` 依旧无法接收消息。

**Comment by CNMathon** [comment]
@ryoii 我依旧受此困惑

**Comment by ryoii** [comment]
@CNMathon 请提供版本号

**Comment by CNMathon** [comment]
> @CNMathon 请提供版本号

以下截图为 `/about` 接口返回项：

![image](https://user-images.githubusercontent.com/44454223/118763989-5b8fc800-b8ab-11eb-90a7-a64c04aab062.png)

**Comment by ryoii** [comment]
本地测试没有问题

**Comment by ryoii** [comment]
尝试升级到 `1.11.0`

**Comment by CNMathon** [comment]
> 尝试升级到 `1.11.0`

@ryoii 尝试中，请稍后

**Comment by CNMathon** [comment]
@ryoii 已尝试，依旧存在该问题

**Comment by CNMathon** [comment]
setting.yml 配置如下：

```yml
cors:
  - "*"
host: 0.0.0.0
port: 8888
authKey: INITKEY28eyhJqK
cacheSize: 4096
enableWebsocket: false
report:
  enable: false
  groupMessage:
    report: true
  friendMessage:
    report: true
  tempMessage:
    report: true
  eventMessage:
    report: true
  destinations: []
  extraHeaders: {}

heartbeat:
  enable: false
  delay: 1000
  period: 15000
  destinations: []
  extraBody: {}

  extraHeaders: {}

```
