### ISSUE TITLE
V2.0-Rc2 无法接受到上报消息

### ISSUE THREAD

**Issue by dalaoshus** [project-mirai/mirai-api-http#357]
控制台内容
![IMG_20210527_220405](https://user-images.githubusercontent.com/79201070/119840334-7d3a2080-bf37-11eb-8227-e7cb56b27db5.jpg)

配置如下
webhook:
    ## 回调(上报)地址
    destinations: 
    - 'http://139.155.26.81/Picture/ind.php'
    - 'localhost:9999/path2'
    - 'localhost:9999/path3'

    ## 额外自定义请求头
    extraHeaders:
      Authorization: 'bearer SV*(&*(SH@ID^G'
      hedaer1: value1
      hedaer2: value2

**Comment by ryoii** [comment]
没有读取到 `destinations`, 检查下配置文件是否有误，将 `destinations` 配置随便填写为一点非 url 的简单值，查看启动时日志显示 `[webhook adapter] is attaching destinations []` 是否有值

如
```
destinations: ["test", "testtest"]
```

**Comment by dalaoshus** [comment]
> 没有读取到 `destinations`, 检查下配置文件是否有误，将 `destinations` 配置随便填写为一点非 url 的简单值，查看启动时日志显示 `[webhook adapter] is attaching destinations []` 是否有值
> 
> 如
> 
> ```
> destinations: ["test", "testtest"]
> ```

你好，的确是配置文件的问题，不过我要如何才能同时启用http和webhook。

adapters:
  - http
  - webhook

enableVerify: true
verifyKey: 6936393

singleMode: false

cacheSize: 4096

adapterSettings:
    http:
    host: 139.155.26.81
    port: 9696
    cors: [*]
  
    webhook:
    destinations: 
    -["http://139.155.26.81/Pictrue/ind.php"]
    extraHeaders:
      Authorization: 'bearer SV*(&*(SH@ID^G'
      hedaer1: value1
      hedaer2: value2

这是我的配置内容，他貌似只会启动一个。

**Comment by ryoii** [comment]
```yaml
## 配置文件中的值，全为默认值

## 启用的 adapter, 内置有 http, ws, reverse-ws, webhook
adapters:
  - http
  - webhook

## 是否开启认证流程, 若为 true 则建立连接时需要验证 verifyKey
## 建议公网连接时开启
enableVerify: true
verifyKey: 6936393

## 开启一些调式信息
debug: false

## 是否开启单 session 模式, 若为 true，则自动创建 session 绑定 console 中登录的 bot
## 开启后，接口中任何 sessionKey 不需要传递参数
## 若 console 中有多个 bot 登录，则行为未定义
## 确保 console 中只有一个 bot 登陆时启用
singleMode: false

## 历史消息的缓存大小
## 同时，也是 http adapter 的消息队列容量
cacheSize: 4096

## adapter 的单独配置，键名与 adapters 项配置相同
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: localhost
    port: 8080
    cors: [*]
  
  webhook:
    ## 回调(上报)地址
    destinations: 
    - 'http://139.155.26.81/Pictrue/ind.php'

    extraHeaders:
      Authorization: 'bearer SV*(&*(SH@ID^G'
```
