### ISSUE TITLE
1.11.0 版本，使用 websocket 获取消息，即使在上报里 groupMessage 为 false 也还是会收到群消息吗？

### ISSUE THREAD

**Issue by XSun771** [project-mirai/mirai-api-http#360]
在 setting.xml 中
```yaml
report:
  enable: true
  groupMessage:
    report: false
```

但后端获取接收消息事件和消息内容的封装是通过 websocket 的，此时群聊事件一样能收到。。这一行为是符合预期的特性还是BUG？如果使用 websocket 是否应该干脆将 report.enable 设置为 false，然后自己在后端程序里根据 type 进行筛选？

有没有可能在 setting.xml 中通过设置直接让 websocket 获取事件时也没有群聊消息？  谢谢
