### ISSUE TITLE
连接websocket时报错：Error: Unexpected server response: 404

### ISSUE THREAD

**Issue by AHpxChina** [project-mirai/mirai-api-http#367]
## setting:
```yml

adapters:
  - http
  - ws

enableVerify: true
verifyKey: 1145141919810

debug: false

singleMode: false

cacheSize: 4096

adapterSettings:
  http:
    host: localhost
    port: 8080
    cors: [*]

  ws:
    host: localhost
    port: 8080
    reservedSyncId: -1
```

## header:
```
verifyKey:1145141919810
qq:xxxxx
```
## console:(MCL)
![image](https://user-images.githubusercontent.com/34391004/122358963-bb9b8c00-cf87-11eb-860a-1d7bfb59818c.png)

## version: v2.0.2
手动安装
