### ISSUE TITLE
严重权限漏洞，/bind未进行校验操作

### ISSUE THREAD

**Issue by c20192138** [project-mirai/mirai-api-http#380]
版本：`2.0.2`

配置文件：
```yml
## 配置文件中的值，全为默认值

## 启用的 adapter, 内置有 http, ws, reverse-ws, webhook
adapters:
  - http

## 是否开启认证流程, 若为 true 则建立连接时需要验证 verifyKey
## 建议公网连接时开启
enableVerify: true
verifyKey: 123456

## 开启一些调式信息
debug: true

## 是否开启单 session 模式, 若为 true，则自动创建 session 绑定 console 中登录的 bot
## 开启后，接口中任何 sessionKey 不需要传递参数
## 若 console 中有多个 bot 登录，则行为未定义
## 确保 console 中只有一个 bot 登陆时启用
singleMode: false

## 历史消息的缓存大小
## 同时，也是 http adapter 的消息队列容量
cacheSize: 4096

## adapter 的单独配置，键名与 adapters 项配置相同
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: localhost
    port: 8888
    cors: [*]

```
请求 `/bind`

参数：
```json
{
    "sessionKey": "sessionKey",
    "qq": 123456
}
```
其中 `sessionKey` 可随便乱填写，无需经过 `/verify` 生成

返回
```json
{"code": 0,"'msg": "success"}
```
`sessionKey` 激活成功，经测试可以正常使用
