### ISSUE TITLE
新版的配置文件是变了吗，

### ISSUE THREAD

**Issue by Huxzhi** [project-mirai/mirai-api-http#472]
查看文档时发现两边的配置文件不一样
https://docs.mirai.mamoe.net/mirai-api-http

还是要退回老版本
```yml
cors:
  - '*'
host: 0.0.0.0
port: 8080
authKey: ########
cacheSize: 4096
enableWebsocket: false
report:
  enable: false
  groupMessage:
    report: true
  friendMessage:
    report: true
  tempMessage:
    report: true
  eventMessage:
    report: true
  destinations: []
  extraHeaders: {}

heartbeat:
  enable: false
  delay: 1000
  period: 15000
  destinations: []
  extraBody: {}

  extraHeaders: {}
```
