### ISSUE TITLE
README的demo配置文件是不是没有更新

### ISSUE THREAD

**Issue by moeik** [project-mirai/mirai-api-http#514]
部署完成后默认生成的是这个
```
cors:
  - http
host: 0.0.0.0
port: 9999
authKey: ********
cacheSize: 4096
enableWebsocket: false
report:
  enable: false
  groupMessage:
    report: true
  friendMessage:
    report: true
  tempMessage:
    report: true
  eventMessage:
    report: true
  destinations: []
  extraHeaders: {}

heartbeat:
  enable: false
  delay: 1000
  period: 15000
  destinations: []
  extraBody: {}

  extraHeaders: {}

```
