### ISSUE TITLE
IP设置问题

### ISSUE THREAD

**Issue by JackLittleE** [project-mirai/mirai-api-http#533]
本机IP为`192.168.0.101`。

在`setting.yml`设置如下。

```
adapterSettings:
  http:
    host: localhost
    port: 5000
    cors: [*]
```

向 `http://localhost:5000/verify` 发送POST请求得到200；向 `http://192.168.0.101:5000/verify` 发送POST请求得到“ 由于目标计算机积极拒绝，无法连接”。

请问这样应该如何解决。

更进一步，在`192.168.0.100`的docker上运行mcl（容器IP为`172.18.0.2`，容器5000端口映射到宿主机5000端口），要用`192.168.0.101`来连接mirai-api-http，请问IP应该如何设置。
