### ISSUE TITLE
`ws` `singleMode:true` 连接上5秒钟会断开, 'singleMode: false'则不会

### ISSUE THREAD

**Issue by sxd1140** [project-mirai/mirai-api-http#746]
`2.9.1`
```yaml
adapters:
  - http
  - ws
debug: true
enableVerify: false
singleMode: true
cacheSize: 4096
adapterSettings:
  http:
    host: 0.0.0.0
    port: 8888
    cors: ["*"]
  ws:
    host: 0.0.0.0
    port: 9999
```
